services:
  - type: web
    name: securevalidator
    runtime: python
    rootDir: Buoi_1/Lab_1/secure-validator-lab
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
